# Generated by Django 5.2.8 on 2025-11-24 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_category_case_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvolvedParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("government_office", "Government Office"),
                            ("public_official", "Public Official"),
                            ("private_company", "Private Company"),
                            ("individual", "Individual"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(blank=True, max_length=255, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="involved_parties",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Involved parties",
            },
        ),
    ]
