# Generated by Django 5.2.8 on 2025-11-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_alter_comment_options_attachment_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attachment",
            name="cases_attac_uploade_7f44c2_idx",
        ),
        migrations.AddField(
            model_name="case",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="If true, case is visible in public API (without personal data).",
            ),
        ),
    ]
